Mvc5/Mvc5/Models/Calculation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Entity;

namespace Mvc5.Models
{
    public class Calculation
    {
        public int Id { get; set; }

        public int Num1 { get; set; }

        public int Num2{ get; set; }

        public CalculatorOperation Operation { get; set; }

        public string Result { get; set; }
    }
}

Mvc5/Mvc5/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Mvc;
using Entity;
using Mvc5.Models;

namespace Mvc5.Controllers
{
    public class CalculatorController : ApiController
    {
        private CalcDb db = new CalcDb();

        [ValidateAntiForgeryToken]
        public IHttpActionResult PostCalculate(CalculatorViewModel model)
        {
            var result = "Invalid data!";
            if (ModelState.IsValid)
            {
                var calc = new Calculator(model.Num1, model.Num2);
                result = calc.ExecuteOperation(model.Operation);

                var calculation = new Calculation
                {
                    Num1 = model.Num1,
                    Num2 = model.Num2,
                    Operation = model.Operation,
                    Result = result
                };
                db.Calculations.Add(calculation);
                db.SaveChanges();
            }

            return Ok(result);
        }

        public IHttpActionResult GetCalculate(CalculatorViewModel model)
        {
            var calc = new Calculator(model.Num1, model.Num2);
            var result = calc.ExecuteOperation(model.Operation);

            return Ok(result);
        }
    }
}

Mvc5/Mvc5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using Mvc5.Models;

namespace Mvc5.Controllers
{
    public class HomeController : Controller
    {
        private CalcDb db = new CalcDb();

        public ActionResult Index(CalculatorViewModel model)
        {
            return View();
        }

        public ActionResult Calculations()
        {
            var model = db.Set<Calculation>();

            return View("Calculations", model);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Calculate(CalculatorViewModel model)
        {
            var calc = new Calculator(model.Num1, model.Num2);
            var result = calc.ExecuteOperation(model.Operation);

            return Json(result);
        }


    }
}

Mvc5/Mvc5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Mvc5/Mvc5/Views/Home/Calculations.cshtml
@model IEnumerable<Mvc5.Models.Calculation>

@{
    ViewBag.Title = "Calculations";
}

<h2>Calculations</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Num1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Num2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Operation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Result)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Num1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Num2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Operation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Result)
        </td>
       
    </tr>
}

</table>

Mvc5/Mvc5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Mvc5/Mvc5/Views/Home/Index.cshtml
@using Entity
@{
    ViewBag.Title = "Home Page";
}

@model CalculatorViewModel

<div class="jumbotron">
    <h1>Бат Сашо The God of MVC</h1>
</div>

@using (Html.BeginForm("", "Calculator", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <h3>Calculator</h3>
        @Html.LabelFor(m => m.Num1)
        @Html.TextBoxFor(m => m.Num1, new { @class = "form-control" })

        @Html.LabelFor(m => m.Num2)
        @Html.TextBoxFor(m => m.Num2, new { @class = "form-control" })

        @Html.LabelFor(m => m.Operation)
        @Html.EnumDropDownListFor(m => m.Operation, new { @class = "form-control" })

        @Html.LabelFor(m => m.Result)
        @Html.TextBoxFor(m => m.Result, new { @class = "form-control", @readonly = "readonly", id = "result" })
    </div>
    <input type="submit" class="btn btn-success" id="submit" />
}

@section Scripts {
    <script>
        console.log("Running .....");
        $(function() {
            var ajaxFormSubmit = function () {
                
                var $form = $(this).parents("form");
                console.log("form", $form.get());
                var url = "/api" + $form.attr("action");
                url = "/api/Calculator";
                //url = "/Home/Calculate";
                console.log("type", url);

                var options = {
                    url: url,
                    type: $form.attr("method"),
                    data: $form.serialize()
                }

                console.log("options", options);

                $.ajax(options)
                    .done(function(data) {
                        var $target = $("#result");
                        $target.val(data);

                        console.log("done", data);

                        //$target.effect("highlight");
                    });

                return false;
            }

            $("#submit").on('click', ajaxFormSubmit);
        });

    </script>
}